spring.config.import=optional:file:./application-local.properties
spring.application.name=travel-invoice
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/navaan}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-init-sql=SET lock_timeout = '10s'
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.use-big-decimal-for-floats=true
spring.jackson.deserialization.fail-on-unknown-properties=true
server.error.include-message=never


