CREATE TABLE transactions (
    id VARCHAR(40) PRIMARY KEY,
    external_id VARCHAR(200) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('flight','hotel','rail','navan_fee')),
    currency CHAR(3) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total DECIMAL(19,2) NOT NULL CHECK (total >= 0),
    metadata JSONB NOT NULL
);
CREATE TABLE transaction_tax_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(40) NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    amount DECIMAL(19,2) NOT NULL CHECK (amount >= 0),
    rate DECIMAL(12,6),
    UNIQUE(transaction_id, position)
);
CREATE TABLE transaction_fee_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(40) NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    amount DECIMAL(19,2) NOT NULL CHECK (amount >= 0),
    UNIQUE(transaction_id, position)
);
CREATE TABLE invoices (
    id VARCHAR(40) PRIMARY KEY,
    currency CHAR(3) NOT NULL,
    total DECIMAL(19,2) NOT NULL CHECK (total >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE invoice_lines (
    id VARCHAR(40) PRIMARY KEY,
    invoice_id VARCHAR(40) NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    transaction_id VARCHAR(40) NOT NULL REFERENCES transactions(id),
    position INTEGER NOT NULL,
    external_id VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    currency CHAR(3) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total DECIMAL(19,2) NOT NULL,
    metadata JSONB NOT NULL,
    UNIQUE(invoice_id, transaction_id),
    UNIQUE(invoice_id, position)
);
CREATE INDEX ix_invoice_lines_transaction ON invoice_lines(transaction_id);
CREATE TABLE invoice_tax_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_line_id VARCHAR(40) NOT NULL REFERENCES invoice_lines(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    rate DECIMAL(12,6),
    UNIQUE(invoice_line_id, position)
);
CREATE TABLE invoice_fee_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_line_id VARCHAR(40) NOT NULL REFERENCES invoice_lines(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    UNIQUE(invoice_line_id, position)
);

